# Generated by Django 3.1.5 on 2021-01-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='days_of_the_week',
            field=models.CharField(choices=[('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THURS', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('BFAST', 'Breakfast'), ("L'NCH", 'Lunch'), ("D'NNER", 'Dinner'), ("D'SERT", 'Dessert')], default='SUN', max_length=6),
        ),
    ]
