# Generated by Django 3.1.5 on 2021-01-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0003_auto_20210130_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekdays',
            name='meal',
            field=models.TextField(default='youroption'),
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
    ]
