# Generated by Django 3.1.5 on 2021-01-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_plans', '0004_auto_20210130_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekdays',
            name='meal',
            field=models.TextField(default='Please enter meal info and recipe'),
        ),
    ]
